const comapnyData = {
  sectors: [
    "Healthcare",
    "Enterprise Software",
    "Industrial",
    "Consumer Technology",
    "Fintech",
    "Clean Energy",
  ],
  subsectors: [
    "Bio Tech & Pharma",
    "Medical Devices",
    "Data Intelligence",
    "AI Infrastructure",
    "SaaS",
    "Aerospace and Defence",
    "Construction",
    "Consumer Electronics",
    "Digital Health",
    "Payments",
    "Blockchain",
    "Battery Tech",
    "Solar Energy",
    "EV Infrastructure",
  ],
  companies: [
    // First 10 companies (already shared)
    {
      name: "NeuroCure Inc.",
      logo: "logo1",
      sector: "Healthcare",
      subsector: "Bio Tech & Pharma",
      forgePrice: "--",
      priceChange: "--",
      shareClass: "Series C",
      postMoneyValuation: "$10.2B",
      pricePerShare: "$xxx",
      amountRaised: "$200MM",
    },
    {
      name: "MediSynth Corp.",
      logo: "logo2",
      sector: "Healthcare",
      subsector: "Medical Devices",
      forgePrice: "$76.45",
      priceChange: "+12.34%",
      shareClass: "Series B",
      postMoneyValuation: "$3.1B",
      pricePerShare: "$xxx",
      amountRaised: "$150MM",
    },
    {
      name: "DataNest",
      logo: "logo3",
      sector: "Enterprise Software",
      subsector: "Data Intelligence",
      forgePrice: "$517.24",
      priceChange: "+73.71%",
      shareClass: "Funding Round",
      postMoneyValuation: "--",
      pricePerShare: "--",
      amountRaised: "--",
    },
    {
      name: "LogicLoop",
      logo: "logo4",
      sector: "Enterprise Software",
      subsector: "AI Infrastructure",
      forgePrice: "$38.76",
      priceChange: "+79.03%",
      shareClass: "Series C",
      postMoneyValuation: "$50B",
      pricePerShare: "$xxx",
      amountRaised: "$6B",
    },
    {
      name: "AeroForce Systems",
      logo: "logo1",
      sector: "Industrial",
      subsector: "Aerospace and Defence",
      forgePrice: "$42.52",
      priceChange: "+42.78%",
      shareClass: "Series G",
      postMoneyValuation: "$28B",
      pricePerShare: "$xxx",
      amountRaised: "$2.58B",
    },
    {
      name: "ConstructoX",
      logo: "logo2",
      sector: "Industrial",
      subsector: "Construction",
      forgePrice: "$0.10",
      priceChange: "-37.5%",
      shareClass: "Series A-2",
      postMoneyValuation: "$3.36B",
      pricePerShare: "$xxx",
      amountRaised: "$74.33MM",
    },
    {
      name: "VoltGrid",
      logo: "logo3",
      sector: "Clean Energy",
      subsector: "EV Infrastructure",
      forgePrice: "$120.89",
      priceChange: "+149.58%",
      shareClass: "Series B",
      postMoneyValuation: "$9.6B",
      pricePerShare: "$xxx",
      amountRaised: "$675MM",
    },
    {
      name: "SunHarvest Energy",
      logo: "logo4",
      sector: "Clean Energy",
      subsector: "Solar Energy",
      forgePrice: "$68.99",
      priceChange: "-3.21%",
      shareClass: "Series A",
      postMoneyValuation: "$1.9B",
      pricePerShare: "$xxx",
      amountRaised: "$300MM",
    },
    {
      name: "PayPulse",
      logo: "logo1",
      sector: "Fintech",
      subsector: "Payments",
      forgePrice: "$154.23",
      priceChange: "+23.09%",
      shareClass: "Series D",
      postMoneyValuation: "$14.2B",
      pricePerShare: "$xxx",
      amountRaised: "$1.2B",
    },
    {
      name: "BlockSafe",
      logo: "logo2",
      sector: "Fintech",
      subsector: "Blockchain",
      forgePrice: "$62.17",
      priceChange: "-12.5%",
      shareClass: "Series B",
      postMoneyValuation: "$3.8B",
      pricePerShare: "$xxx",
      amountRaised: "$560MM",
    },

    // Remaining 40 companies
    {
      name: "HealthCore AI",
      logo: "logo3",
      sector: "Healthcare",
      subsector: "Digital Health",
      forgePrice: "$89.45",
      priceChange: "+15.67%",
      shareClass: "Series A",
      postMoneyValuation: "$1.5B",
      pricePerShare: "$xxx",
      amountRaised: "$400MM",
    },
    {
      name: "MediLoop",
      logo: "logo4",
      sector: "Healthcare",
      subsector: "Medical Devices",
      forgePrice: "$42.75",
      priceChange: "+8.44%",
      shareClass: "Series C",
      postMoneyValuation: "$2.2B",
      pricePerShare: "$xxx",
      amountRaised: "$300MM",
    },
    {
      name: "Visionlytics",
      logo: "logo1",
      sector: "Enterprise Software",
      subsector: "SaaS",
      forgePrice: "$109.23",
      priceChange: "+28.6%",
      shareClass: "Series D",
      postMoneyValuation: "$6.8B",
      pricePerShare: "$xxx",
      amountRaised: "$850MM",
    },
    {
      name: "CodeCloud",
      logo: "logo2",
      sector: "Enterprise Software",
      subsector: "AI Infrastructure",
      forgePrice: "$78.23",
      priceChange: "+34.2%",
      shareClass: "Series C",
      postMoneyValuation: "$5.6B",
      pricePerShare: "$xxx",
      amountRaised: "$450MM",
    },
    {
      name: "AutoBuild",
      logo: "logo3",
      sector: "Industrial",
      subsector: "Construction",
      forgePrice: "$21.78",
      priceChange: "-15.2%",
      shareClass: "Series B",
      postMoneyValuation: "$900MM",
      pricePerShare: "$xxx",
      amountRaised: "$140MM",
    },
    {
      name: "SteelLogic",
      logo: "logo4",
      sector: "Industrial",
      subsector: "Aerospace and Defence",
      forgePrice: "$134.55",
      priceChange: "+67.1%",
      shareClass: "Series E",
      postMoneyValuation: "$18.9B",
      pricePerShare: "$xxx",
      amountRaised: "$3.2B",
    },
    {
      name: "CleanVolt",
      logo: "logo1",
      sector: "Clean Energy",
      subsector: "Battery Tech",
      forgePrice: "$93.20",
      priceChange: "+22.7%",
      shareClass: "Series B",
      postMoneyValuation: "$4.5B",
      pricePerShare: "$xxx",
      amountRaised: "$500MM",
    },
    {
      name: "BrightCell",
      logo: "logo2",
      sector: "Clean Energy",
      subsector: "Solar Energy",
      forgePrice: "$31.57",
      priceChange: "-8.8%",
      shareClass: "Series A",
      postMoneyValuation: "$2.1B",
      pricePerShare: "$xxx",
      amountRaised: "$280MM",
    },
    {
      name: "SpendLite",
      logo: "logo3",
      sector: "Fintech",
      subsector: "Payments",
      forgePrice: "$74.30",
      priceChange: "+19.5%",
      shareClass: "Series C",
      postMoneyValuation: "$3.4B",
      pricePerShare: "$xxx",
      amountRaised: "$680MM",
    },
    {
      name: "ChainFlow",
      logo: "logo4",
      sector: "Fintech",
      subsector: "Blockchain",
      forgePrice: "$59.89",
      priceChange: "-6.5%",
      shareClass: "Series D",
      postMoneyValuation: "$5.6B",
      pricePerShare: "$xxx",
      amountRaised: "$920MM",
    },
    {
      name: "ThermoGenix",
      logo: "logo1",
      sector: "Healthcare",
      subsector: "Bio Tech & Pharma",
      forgePrice: "$85.47",
      priceChange: "+9.9%",
      shareClass: "Series B",
      postMoneyValuation: "$2.9B",
      pricePerShare: "$xxx",
      amountRaised: "$360MM",
    },
    {
      name: "DeviceNova",
      logo: "logo2",
      sector: "Healthcare",
      subsector: "Medical Devices",
      forgePrice: "$64.33",
      priceChange: "+4.1%",
      shareClass: "Series A",
      postMoneyValuation: "$1.2B",
      pricePerShare: "$xxx",
      amountRaised: "$110MM",
    },
    {
      name: "DeepStack AI",
      logo: "logo3",
      sector: "Enterprise Software",
      subsector: "AI Infrastructure",
      forgePrice: "$158.78",
      priceChange: "+89.3%",
      shareClass: "Series D",
      postMoneyValuation: "$12.7B",
      pricePerShare: "$xxx",
      amountRaised: "$2.4B",
    },
    {
      name: "CloudMesh",
      logo: "logo4",
      sector: "Enterprise Software",
      subsector: "SaaS",
      forgePrice: "$101.22",
      priceChange: "+17.2%",
      shareClass: "Series C",
      postMoneyValuation: "$6.3B",
      pricePerShare: "$xxx",
      amountRaised: "$1.1B",
    },
    {
      name: "InfraCore",
      logo: "logo1",
      sector: "Industrial",
      subsector: "Construction",
      forgePrice: "$32.00",
      priceChange: "+5.6%",
      shareClass: "Series B",
      postMoneyValuation: "$870MM",
      pricePerShare: "$xxx",
      amountRaised: "$230MM",
    },
    {
      name: "TitanAero",
      logo: "logo2",
      sector: "Industrial",
      subsector: "Aerospace and Defence",
      forgePrice: "$195.50",
      priceChange: "+62.8%",
      shareClass: "Series E",
      postMoneyValuation: "$21.4B",
      pricePerShare: "$xxx",
      amountRaised: "$3.7B",
    },
    {
      name: "SolarNova",
      logo: "logo3",
      sector: "Clean Energy",
      subsector: "Solar Energy",
      forgePrice: "$88.77",
      priceChange: "-2.3%",
      shareClass: "Series A",
      postMoneyValuation: "$3.1B",
      pricePerShare: "$xxx",
      amountRaised: "$470MM",
    },
    {
      name: "EcoWatt",
      logo: "logo4",
      sector: "Clean Energy",
      subsector: "Battery Tech",
      forgePrice: "$44.12",
      priceChange: "+7.1%",
      shareClass: "Series B",
      postMoneyValuation: "$2.4B",
      pricePerShare: "$xxx",
      amountRaised: "$380MM",
    },
    {
      name: "CredixPay",
      logo: "logo1",
      sector: "Fintech",
      subsector: "Payments",
      forgePrice: "$114.59",
      priceChange: "+12.2%",
      shareClass: "Series C",
      postMoneyValuation: "$8.7B",
      pricePerShare: "$xxx",
      amountRaised: "$1.5B",
    },
    {
      name: "NovaChain",
      logo: "logo2",
      sector: "Fintech",
      subsector: "Blockchain",
      forgePrice: "$72.34",
      priceChange: "+2.9%",
      shareClass: "Series A",
      postMoneyValuation: "$2.8B",
      pricePerShare: "$xxx",
      amountRaised: "$610MM",
    },
    {
      name: "MedAI Diagnostics",
      logo: "logo3",
      sector: "Healthcare",
      subsector: "Digital Health",
      forgePrice: "$93.90",
      priceChange: "+25.4%",
      shareClass: "Series B",
      postMoneyValuation: "$4.4B",
      pricePerShare: "$xxx",
      amountRaised: "$540MM",
    },
    {
      name: "PulseTech",
      logo: "logo4",
      sector: "Consumer Technology",
      subsector: "Consumer Electronics",
      forgePrice: "$56.79",
      priceChange: "+8.3%",
      shareClass: "Series A",
      postMoneyValuation: "$1.9B",
      pricePerShare: "$xxx",
      amountRaised: "$290MM",
    },
    {
      name: "NeoDevices",
      logo: "logo1",
      sector: "Consumer Technology",
      subsector: "Consumer Electronics",
      forgePrice: "$71.22",
      priceChange: "-3.7%",
      shareClass: "Series B",
      postMoneyValuation: "$2.5B",
      pricePerShare: "$xxx",
      amountRaised: "$470MM",
    },
    {
      name: "NeuroCure Inc.",
      logo: "logo1",
      sector: "Healthcare",
      subsector: "Bio Tech & Pharma",
      forgePrice: "--",
      priceChange: "--",
      shareClass: "Series C",
      postMoneyValuation: "$10.2B",
      pricePerShare: "$xxx",
      amountRaised: "$200MM",
    },
    {
      name: "MediSynth Corp.",
      logo: "logo2",
      sector: "Healthcare",
      subsector: "Medical Devices",
      forgePrice: "$76.45",
      priceChange: "+12.34%",
      shareClass: "Series B",
      postMoneyValuation: "$3.1B",
      pricePerShare: "$xxx",
      amountRaised: "$150MM",
    },
    {
      name: "DataNest",
      logo: "logo3",
      sector: "Enterprise Software",
      subsector: "Data Intelligence",
      forgePrice: "$517.24",
      priceChange: "+73.71%",
      shareClass: "Funding Round",
      postMoneyValuation: "--",
      pricePerShare: "--",
      amountRaised: "--",
    },
    {
      name: "LogicLoop",
      logo: "logo4",
      sector: "Enterprise Software",
      subsector: "AI Infrastructure",
      forgePrice: "$38.76",
      priceChange: "+79.03%",
      shareClass: "Series C",
      postMoneyValuation: "$50B",
      pricePerShare: "$xxx",
      amountRaised: "$6B",
    },
    {
      name: "AeroForce Systems",
      logo: "logo1",
      sector: "Industrial",
      subsector: "Aerospace and Defence",
      forgePrice: "$42.52",
      priceChange: "+42.78%",
      shareClass: "Series G",
      postMoneyValuation: "$28B",
      pricePerShare: "$xxx",
      amountRaised: "$2.58B",
    },
    {
      name: "ConstructoX",
      logo: "logo2",
      sector: "Industrial",
      subsector: "Construction",
      forgePrice: "$0.10",
      priceChange: "-37.5%",
      shareClass: "Series A-2",
      postMoneyValuation: "$3.36B",
      pricePerShare: "$xxx",
      amountRaised: "$74.33MM",
    },
    {
      name: "VoltGrid",
      logo: "logo3",
      sector: "Clean Energy",
      subsector: "EV Infrastructure",
      forgePrice: "$120.89",
      priceChange: "+149.58%",
      shareClass: "Series B",
      postMoneyValuation: "$9.6B",
      pricePerShare: "$xxx",
      amountRaised: "$675MM",
    },
    {
      name: "SunHarvest Energy",
      logo: "logo4",
      sector: "Clean Energy",
      subsector: "Solar Energy",
      forgePrice: "$68.99",
      priceChange: "-3.21%",
      shareClass: "Series A",
      postMoneyValuation: "$1.9B",
      pricePerShare: "$xxx",
      amountRaised: "$300MM",
    },
    {
      name: "PayPulse",
      logo: "logo1",
      sector: "Fintech",
      subsector: "Payments",
      forgePrice: "$154.23",
      priceChange: "+23.09%",
      shareClass: "Series D",
      postMoneyValuation: "$14.2B",
      pricePerShare: "$xxx",
      amountRaised: "$1.2B",
    },
    {
      name: "BlockSafe",
      logo: "logo2",
      sector: "Fintech",
      subsector: "Blockchain",
      forgePrice: "$62.17",
      priceChange: "-12.5%",
      shareClass: "Series B",
      postMoneyValuation: "$3.8B",
      pricePerShare: "$xxx",
      amountRaised: "$560MM",
    },
  ],
};

export default comapnyData;
